#!/usr/bin/env python3
"""
AI News Daily - liwenwei9 专属版本（支持中英文）
"""

import os
import json
import datetime
import pytz
from typing import List, Dict, Any
import arxiv
import feedparser

class AINewsDaily:
    def __init__(self):
        self.github_user = "liwenwei9"
        self.repo_name = "ai-news-daily"
        self.website_url = f"https://{self.github_user}.github.io/{self.repo_name}/"
        
        # 创建输出目录
        os.makedirs('docs', exist_ok=True)
        
        # 多语言文本
        self.texts = {
            'zh': {
                'site_title': 'AI News Daily - liwenwei9',
                'site_description': '每日AI资讯聚合网站',
                'subtitle': 'liwenwei9的专属AI资讯站',
                'today_papers': '今日论文',
                'today_news': '今日新闻',
                'total_content': '总计内容',
                'paper_selection': '今日论文精选',
                'news_selection': '今日新闻精选',
                'authors': '作者',
                'category': '分类',
                'date': '日期',
                'source': '来源',
                'download_pdf': '下载PDF',
                'arxiv_page': 'arXiv页面',
                'read_original': '阅读原文',
                'auto_generated': '由AI自动生成',
                'daily_update': '每日更新',
                'exclusive_version': 'liwenwei9的专属版本',
                'last_update': '最后更新',
                'generation_time': '生成时间',
                'view_project': '查看GitHub项目',
                'language_zh': '中文',
                'language_en': 'English',
                'switch_language': '切换语言',
                'no_paper_data': '暂无论文数据',
                'no_news_data': '暂无新闻数据',
                'current_time': '当前时间',
                'published': '发布时间'
            },
            'en': {
                'site_title': 'AI News Daily - liwenwei9',
                'site_description': 'Daily AI News Aggregator',
                'subtitle': 'liwenwei9\'s Exclusive AI News Station',
                'today_papers': 'Today\'s Papers',
                'today_news': 'Today\'s News',
                'total_content': 'Total Content',
                'paper_selection': 'Today\'s Paper Selection',
                'news_selection': 'Today\'s News Selection',
                'authors': 'Authors',
                'category': 'Category',
                'date': 'Date',
                'source': 'Source',
                'download_pdf': 'Download PDF',
                'arxiv_page': 'arXiv Page',
                'read_original': 'Read Original',
                'auto_generated': 'Auto-generated by AI',
                'daily_update': 'Daily Update',
                'exclusive_version': 'liwenwei9 Exclusive Version',
                'last_update': 'Last Update',
                'generation_time': 'Generation Time',
                'view_project': 'View GitHub Project',
                'language_zh': '中文',
                'language_en': 'English',
                'switch_language': 'Switch Language',
                'no_paper_data': 'No paper data available',
                'no_news_data': 'No news data available',
                'current_time': 'Current Time',
                'published': 'Published'
            }
        }
    
    def get_arxiv_papers(self) -> List[Dict[str, Any]]:
        """从arXiv获取AI论文"""
        print("📚 获取arXiv论文...")
        
        papers = []
        try:
            client = arxiv.Client()
            search = arxiv.Search(
                query="cat:cs.AI OR cat:cs.LG",
                max_results=5,
                sort_by=arxiv.SortCriterion.SubmittedDate,
                sort_order=arxiv.SortOrder.Descending
            )
            
            for result in client.results(search):
                paper = {
                    'id': result.entry_id.split('/')[-1],
                    'title': result.title,
                    'authors': [author.name for author in result.authors[:3]],
                    'summary': result.summary[:200] + '...',
                    'published': result.published.strftime('%Y-%m-%d'),
                    'pdf_url': result.pdf_url,
                    'arxiv_url': f"https://arxiv.org/abs/{result.entry_id.split('/')[-1]}",
                    'category': result.primary_category
                }
                papers.append(paper)
            
            print(f"✅ 获取到 {len(papers)} 篇论文")
            
        except Exception as e:
            print(f"⚠️ 获取论文失败: {e}")
            # 返回示例数据
            papers = [{
                'id': '2401.12345',
                'title': 'Large Language Models: A Survey',
                'authors': ['AI Researcher'],
                'summary': 'Recent advances in large language models...',
                'published': datetime.datetime.now().strftime('%Y-%m-%d'),
                'pdf_url': 'https://arxiv.org/pdf/2401.12345.pdf',
                'arxiv_url': 'https://arxiv.org/abs/2401.12345',
                'category': 'cs.AI'
            }]
        
        return papers
    
    def get_tech_news(self) -> List[Dict[str, Any]]:
        """获取科技新闻"""
        print("📰 获取科技新闻...")
        
        news_items = []
        try:
            # 使用MIT Technology Review的RSS
            feed = feedparser.parse('https://www.technologyreview.com/feed/')
            
            for entry in feed.entries[:5]:
                # 过滤AI相关新闻
                text = f"{entry.title} {entry.get('summary', '')}"
                if any(keyword in text.lower() for keyword in ['ai', 'artificial intelligence', 'machine learning']):
                    news = {
                        'title': entry.title,
                        'source': 'MIT Technology Review',
                        'link': entry.link,
                        'summary': entry.get('summary', '')[:150] + '...',
                        'published': entry.get('published', datetime.datetime.now().strftime('%Y-%m-%d')),
                        'content': entry.get('content', [{}])[0].get('value', '')[:100] + '...' if entry.get('content') else ''
                    }
                    news_items.append(news)
            
            print(f"✅ 获取到 {len(news_items)} 条新闻")
            
        except Exception as e:
            print(f"⚠️ 获取新闻失败: {e}")
            # 返回示例数据
            news_items = [{
                'title': 'AI Breakthrough Announced',
                'source': 'Tech News',
                'link': 'https://example.com',
                'summary': 'Major breakthrough in artificial intelligence...',
                'published': datetime.datetime.now().strftime('%Y-%m-%d'),
                'content': 'Detailed content...'
            }]
        
        return news_items

    def generate_html(self, papers: List[Dict], news: List[Dict]) -> str:
        """生成HTML页面（支持多语言）"""
        now = datetime.datetime.now(pytz.timezone('Asia/Shanghai'))
        date_str = now.strftime('%Y年%m月%d日')
        time_str = now.strftime('%H:%M:%S')
        
        # 构建HTML（包含多语言支持和切换功能）
        html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI News Daily - liwenwei9</title>
    <meta name="description" content="每日AI资讯聚合网站 - 支持中英文切换">
    <style>
        :root {{
            --primary: #667eea;
            --secondary: #764ba2;
            --bg: #f5f7fa;
            --card: #ffffff;
            --text: #333;
        }}
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: var(--text);
            background: var(--bg);
            min-height: 100vh;
        }}
        
        .container {{
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
        }}
        
        /* 语言切换器样式 */
        .language-switcher {{
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
            display: flex;
            gap: 5px;
            background: rgba(255,255,255,0.9);
            padding: 8px 12px;
            border-radius: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            backdrop-filter: blur(10px);
        }}
        
        .lang-btn {{
            padding: 6px 12px;
            border: none;
            background: transparent;
            color: #666;
            cursor: pointer;
            border-radius: 15px;
            font-size: 0.9rem;
            transition: all 0.3s;
        }}
        
        .lang-btn:hover {{
            background: #f0f0f0;
        }}
        
        .lang-btn.active {{
            background: var(--primary);
            color: white;
        }}
        
        header {{
            text-align: center;
            padding: 30px;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            color: white;
            border-radius: 10px;
            margin-bottom: 30px;
            position: relative;
        }}
        
        h1 {{
            font-size: 2.5rem;
            margin-bottom: 10px;
        }}
        
        .subtitle {{
            font-size: 1.1rem;
            opacity: 0.9;
            margin-bottom: 15px;
        }}
        
        .date {{
            background: rgba(255,255,255,0.2);
            padding: 8px 16px;
            border-radius: 20px;
            display: inline-block;
        }}
        
        .stats {{
            display: flex;
            justify-content: center;
            gap: 20px;
            margin: 20px 0;
            flex-wrap: wrap;
        }}
        
        .stat-card {{
            background: rgba(255,255,255,0.9);
            padding: 15px 25px;
            border-radius: 10px;
            text-align: center;
            min-width: 120px;
        }}
        
        .stat-number {{
            font-size: 1.8rem;
            font-weight: bold;
            color: var(--primary);
        }}
        
        .content {{
            background: var(--card);
            border-radius: 15px;
            padding: 30px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.08);
        }}
        
        .section {{
            margin-bottom: 30px;
        }}
        
        .section-title {{
            font-size: 1.5rem;
            color: var(--text);
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid var(--primary);
        }}
        
        .item-card {{
            background: #f8f9fa;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 15px;
            border-left: 3px solid var(--primary);
        }}
        
        .item-title {{
            font-size: 1.2rem;
            color: #2d3748;
            margin-bottom: 10px;
        }}
        
        .item-meta {{
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
            margin-bottom: 10px;
            font-size: 0.9rem;
            color: #666;
        }}
        
        .item-summary {{
            color: #4a5568;
            line-height: 1.6;
            margin-bottom: 15px;
            padding: 15px;
            background: white;
            border-radius: 8px;
        }}
        
        .btn {{
            display: inline-block;
            padding: 8px 16px;
            background: var(--primary);
            color: white;
            text-decoration: none;
            border-radius: 6px;
            margin-right: 10px;
            transition: background 0.3s;
        }}
        
        .btn:hover {{
            background: #5a67d8;
        }}
        
        footer {{
            text-align: center;
            padding: 30px;
            color: #666;
            margin-top: 30px;
        }}
        
        @media (max-width: 768px) {{
            .container {{ padding: 10px; }}
            h1 {{ font-size: 2rem; }}
            .content {{ padding: 20px; }}
            .language-switcher {{
                top: 10px;
                right: 10px;
                padding: 6px 10px;
            }}
            .lang-btn {{
                padding: 4px 8px;
                font-size: 0.8rem;
            }}
        }}
    </style>
</head>
<body>
    <!-- 语言切换器 -->
    <div class="language-switcher">
        <button class="lang-btn active" data-lang="zh">中文</button>
        <button class="lang-btn" data-lang="en">English</button>
    </div>
    
    <div class="container">
        <header>
            <h1 data-i18n="site_title">🤖 AI News Daily</h1>
            <div class="subtitle" data-i18n="subtitle">liwenwei9的专属AI资讯站</div>
            <div class="date">📅 <span id="header-date">{date_str}</span></div>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-number">{len(papers)}</div>
                    <div data-i18n="today_papers">📚 今日论文</div>
                </div>
                <div class="stat-card">
                    <div class="stat-number">{len(news)}</div>
                    <div data-i18n="today_news">📰 今日新闻</div>
                </div>
                <div class="stat-card">
                    <div class="stat-number">{len(papers) + len(news)}</div>
                    <div data-i18n="total_content">✨ 总计内容</div>
                </div>
            </div>
        </header>
        
        <div class="content">
            <section class="section">
                <h2 class="section-title" data-i18n="paper_selection">📚 今日论文精选</h2>
                {self._generate_papers_html(papers)}
            </section>
            
            <section class="section">
                <h2 class="section-title" data-i18n="news_selection">📰 今日新闻精选</h2>
                {self._generate_news_html(news)}
            </section>
        </div>
        
        <footer>
            <p data-i18n="footer_desc">🤖 由AI自动生成 | 每日更新 | liwenwei9的专属版本</p>
            <p id="footer-time">
                <span data-i18n="last_update">📅 最后更新</span>: <span id="update-date">{date_str}</span> | 
                <span data-i18n="current_time">⏰ 当前时间</span>: <span id="current-time">{time_str}</span>
            </p>
            <p>🚀 <a href="https://github.com/{self.github_user}/{self.repo_name}" target="_blank" style="color: #667eea;" data-i18n="view_project">查看GitHub项目</a></p>
        </footer>
    </div>
    
    <script>
        // 多语言配置（和Python端保持一致）
        const translations = {{
            zh: {{
                site_title: '🤖 AI News Daily',
                site_description: '每日AI资讯聚合网站',
                subtitle: 'liwenwei9的专属AI资讯站',
                today_papers: '📚 今日论文',
                today_news: '📰 今日新闻',
                total_content: '✨ 总计内容',
                paper_selection: '📚 今日论文精选',
                news_selection: '📰 今日新闻精选',
                authors: '👨‍🎓 作者',
                category: '🏷️ 分类',
                date: '📅 日期',
                source: '🏢 来源',
                download_pdf: '📄 下载PDF',
                arxiv_page: '🔗 arXiv页面',
                read_original: '🔗 阅读原文',
                auto_generated: '由AI自动生成',
                daily_update: '每日更新',
                exclusive_version: 'liwenwei9的专属版本',
                last_update: '📅 最后更新',
                generation_time: '⏰ 生成时间',
                view_project: '查看GitHub项目',
                language_zh: '中文',
                language_en: 'English',
                switch_language: '切换语言',
                no_paper_data: '暂无论文数据',
                no_news_data: '暂无新闻数据',
                current_time: '⏰ 当前时间',
                published: '📅 发布时间',
                footer_desc: '🤖 由AI自动生成 | 每日更新 | liwenwei9的专属版本'
            }},
            en: {{
                site_title: '🤖 AI News Daily',
                site_description: 'Daily AI News Aggregator',
                subtitle: 'liwenwei9\\'s Exclusive AI News Station',
                today_papers: '📚 Today\\'s Papers',
                today_news: '📰 Today\\'s News',
                total_content: '✨ Total Content',
                paper_selection: '📚 Today\\'s Paper Selection',
                news_selection: '📰 Today\\'s News Selection',
                authors: '👨‍🎓 Authors',
                category: '🏷️ Category',
                date: '📅 Date',
                source: '🏢 Source',
                download_pdf: '📄 Download PDF',
                arxiv_page: '🔗 arXiv Page',
                read_original: '🔗 Read Original',
                auto_generated: 'Auto-generated by AI',
                daily_update: 'Daily Update',
                exclusive_version: 'liwenwei9 Exclusive Version',
                last_update: '📅 Last Update',
                generation_time: '⏰ Generation Time',
                view_project: 'View GitHub Project',
                language_zh: '中文',
                language_en: 'English',
                switch_language: 'Switch Language',
                no_paper_data: 'No paper data available',
                no_news_data: 'No news data available',
                current_time: '⏰ Current Time',
                published: '📅 Published',
                footer_desc: '🤖 Auto-generated by AI | Daily Update | liwenwei9 Exclusive Version'
            }}
        }};
        
        // 全局当前语言变量
        let currentLang = 'zh';
        
        // 获取本地存储的语言设置
        function getSavedLanguage() {{
            return localStorage.getItem('ai-news-language') || 'zh';
        }}
        
        // 保存语言设置到本地存储
        function saveLanguage(lang) {{
            localStorage.setItem('ai-news-language', lang);
            currentLang = lang;
        }}
        
        // 更新页面所有多语言文本
        function updateLanguageContent(lang) {{
            // 1. 更新页面标题
            document.title = translations[lang].site_title;
            
            // 2. 更新所有带data-i18n属性的元素
            document.querySelectorAll('[data-i18n]').forEach(el => {{
                const key = el.getAttribute('data-i18n');
                if (translations[lang][key]) {{
                    el.textContent = translations[lang][key];
                }}
            }});
            
            // 3. 更新论文/新闻卡片中的固定文本
            updateItemCards(lang);
            
            // 4. 更新语言按钮状态
            document.querySelectorAll('.lang-btn').forEach(btn => {{
                btn.classList.remove('active');
                if (btn.dataset.lang === lang) {{
                    btn.classList.add('active');
                }}
            }});
        }}
        
        // 更新论文/新闻卡片中的多语言文本
        function updateItemCards(lang) {{
            // 更新论文卡片的元数据文本
            document.querySelectorAll('.item-card').forEach(card => {{
                // 论文卡片
                const authorLabel = card.querySelector('.author-label');
                if (authorLabel) authorLabel.textContent = translations[lang].authors + ':';
                
                const categoryLabel = card.querySelector('.category-label');
                if (categoryLabel) categoryLabel.textContent = translations[lang].category + ':';
                
                const dateLabel = card.querySelector('.date-label');
                if (dateLabel) dateLabel.textContent = translations[lang].date + ':';
                
                const sourceLabel = card.querySelector('.source-label');
                if (sourceLabel) sourceLabel.textContent = translations[lang].source + ':';
                
                const publishedLabel = card.querySelector('.published-label');
                if (publishedLabel) publishedLabel.textContent = translations[lang].published + ':';
                
                // 更新按钮文本
                const pdfBtn = card.querySelector('.pdf-btn');
                if (pdfBtn) pdfBtn.textContent = translations[lang].download_pdf;
                
                const arxivBtn = card.querySelector('.arxiv-btn');
                if (arxivBtn) arxivBtn.textContent = translations[lang].arxiv_page;
                
                const originalBtn = card.querySelector('.original-btn');
                if (originalBtn) originalBtn.textContent = translations[lang].read_original;
                
                // 更新空数据提示
                const noData = card.querySelector('.no-data');
                if (noData) {{
                    if (card.closest('[data-section="papers"]')) {{
                        noData.textContent = translations[lang].no_paper_data;
                    }} else if (card.closest('[data-section="news"]')) {{
                        noData.textContent = translations[lang].no_news_data;
                    }}
                }}
            }});
        }}
        
        // 更新时间显示（保留多语言）
        function updateTimeDisplay() {{
            const now = new Date();
            const updateDateEl = document.getElementById('update-date');
            const currentTimeEl = document.getElementById('current-time');
            
            if (updateDateEl && currentTimeEl) {{
                if (currentLang === 'zh') {{
                    updateDateEl.textContent = now.toLocaleDateString('zh-CN');
                    currentTimeEl.textContent = now.toLocaleTimeString('zh-CN');
                }} else {{
                    updateDateEl.textContent = now.toLocaleDateString('en-US');
                    currentTimeEl.textContent = now.toLocaleTimeString('en-US');
                }}
            }}
        }}
        
        // 初始化
        document.addEventListener('DOMContentLoaded', function() {{
            // 获取并设置初始语言
            currentLang = getSavedLanguage();
            updateLanguageContent(currentLang);
            
            // 添加语言切换按钮事件
            document.querySelectorAll('.lang-btn').forEach(btn => {{
                btn.addEventListener('click', function() {{
                    const lang = this.dataset.lang;
                    saveLanguage(lang);
                    updateLanguageContent(lang);
                    updateTimeDisplay(); // 更新时间格式
                }});
            }});
            
            // 定时更新时间（不覆盖多语言文本）
            updateTimeDisplay();
            setInterval(updateTimeDisplay, 1000);
        }});
    </script>
</body>
</html>'''
        
        return html

    def _generate_papers_html(self, papers: List[Dict]) -> str:
        """生成论文HTML（添加多语言标签）"""
        if not papers:
            return '<p class="no-data" data-i18n="no_paper_data">暂无论文数据</p>'
        
        html_parts = []
        for paper in papers:
            html = f'''
            <div class="item-card">
                <h3 class="item-title">{paper['title']}</h3>
                <div class="item-meta">
                    <span class="author-label" data-i18n="authors">👨‍🎓 作者</span>: {', '.join(paper['authors'])}
                    <span class="category-label" data-i18n="category">🏷️ 分类</span>: {paper['category']}
                    <span class="date-label" data-i18n="date">📅 日期</span>: {paper['published']}
                </div>
                <div class="item-summary">
                    {paper['summary']}
                </div>
                <div>
                    <a href="{paper['pdf_url']}" class="btn pdf-btn" target="_blank" data-i18n="download_pdf">📄 下载PDF</a>
                    <a href="{paper['arxiv_url']}" class="btn arxiv-btn" target="_blank" data-i18n="arxiv_page">🔗 arXiv页面</a>
                </div>
            </div>
            '''
            html_parts.append(html)
        
        return '\n'.join(html_parts)
    
    def _generate_news_html(self, news: List[Dict]) -> str:
        """生成新闻HTML（添加多语言标签）"""
        if not news:
            return '<p class="no-data" data-i18n="no_news_data">暂无新闻数据</p>'
        
        html_parts = []
        for item in news:
            html = f'''
            <div class="item-card">
                <h3 class="item-title">{item['title']}</h3>
                <div class="item-meta">
                    <span class="source-label" data-i18n="source">🏢 来源</span>: {item['source']}
                    <span class="published-label" data-i18n="published">📅 发布时间</span>: {item['published']}
                </div>
                <div class="item-summary">
                    {item['summary']}
                </div>
                <div>
                    <a href="{item['link']}" class="btn original-btn" target="_blank" data-i18n="read_original">🔗 阅读原文</a>
                </div>
            </div>
            '''
            html_parts.append(html)
        
        return '\n'.join(html_parts)
    
    def run(self):
        """主运行函数"""
        print("🚀 AI News Daily 开始运行...")
        print(f"👤 GitHub用户: {self.github_user}")
        print(f"🌐 网站地址: {self.website_url}")
        print("🌐 支持语言: 中文 / English")
        
        try:
            # 获取数据
            papers = self.get_arxiv_papers()
            news = self.get_tech_news()
            
            # 生成HTML
            html = self.generate_html(papers, news)
            
            # 保存文件
            with open('docs/index.html', 'w', encoding='utf-8') as f:
                f.write(html)
            
            print("✅ 网站生成完成！")
            print(f"📁 文件保存: docs/index.html")
            print(f"🌐 访问地址: {self.website_url}")
            print("🎯 功能: 中英文切换 | 每日自动更新")
            
        except Exception as e:
            print(f"❌ 运行失败: {e}")
            import traceback
            traceback.print_exc()

if __name__ == '__main__':
    app = AINewsDaily()
    app.run()
