#!/usr/bin/env python3
"""
AI News Daily - liwenwei9 专属版本（改进版）
参考 ai-brief.liziran.com 的设计，添加一句话概要功能
"""

import os
import json
import datetime
import pytz
from typing import List, Dict, Any
import arxiv
import feedparser
import re

class AINewsDaily:
    def __init__(self):
        self.github_user = "liwenwei9"
        self.repo_name = "ai-news-daily"
        self.website_url = f"https://{self.github_user}.github.io/{self.repo_name}/"

        # 创建输出目录
        os.makedirs('docs', exist_ok=True)

        # 多语言文本
        self.texts = {
            'zh': {
                'site_title': 'AI News Daily - liwenwei9',
                'site_description': '每日AI资讯聚合网站',
                'subtitle': '每日AI前沿论文与新闻精选',
                'slogan': '每天3分钟，把握AI前沿动态',
                'today_papers': '今日论文',
                'today_news': '今日新闻',
                'total_content': '总计内容',
                'paper_selection': '📚 今日论文精选',
                'news_selection': '📰 今日新闻精选',
                'from_papers': '从 {total} 篇论文中筛选',
                'authors': '作者',
                'category': '分类',
                'date': '日期',
                'source': '来源',
                'download_pdf': 'PDF',
                'arxiv_page': 'arXiv',
                'read_original': '阅读原文',
                'auto_generated': '由AI自动生成',
                'daily_update': '每日更新',
                'exclusive_version': 'liwenwei9的专属版本',
                'last_update': '最后更新',
                'generation_time': '生成时间',
                'view_project': '查看GitHub项目',
                'language_zh': '中文',
                'language_en': 'English',
                'switch_language': '切换语言',
                'no_paper_data': '暂无论文数据',
                'no_news_data': '暂无新闻数据'
            },
            'en': {
                'site_title': 'AI News Daily - liwenwei9',
                'site_description': 'Daily AI News Aggregator',
                'subtitle': 'Daily AI Paper & News Selection',
                'slogan': '3 minutes a day to stay ahead in AI',
                'today_papers': 'Papers',
                'today_news': 'News',
                'total_content': 'Total',
                'paper_selection': '📚 Today\'s Paper Selection',
                'news_selection': '📰 Today\'s News Selection',
                'from_papers': 'Selected from {total} papers',
                'authors': 'Authors',
                'category': 'Category',
                'date': 'Date',
                'source': 'Source',
                'download_pdf': 'PDF',
                'arxiv_page': 'arXiv',
                'read_original': 'Read More',
                'auto_generated': 'Auto-generated by AI',
                'daily_update': 'Daily Update',
                'exclusive_version': 'liwenwei9 Exclusive',
                'last_update': 'Last Update',
                'generation_time': 'Generated',
                'view_project': 'View on GitHub',
                'language_zh': '中文',
                'language_en': 'English',
                'switch_language': 'Switch Language',
                'no_paper_data': 'No papers available',
                'no_news_data': 'No news available'
            }
        }

    def generate_one_sentence_summary(self, text: str, max_length: int = 60) -> str:
        """
        生成一句话概要
        简化版本：提取第一句话或前N个字符
        未来可以接入AI API进行智能总结
        """
        # 移除多余空白
        text = ' '.join(text.split())

        # 尝试提取第一句话
        sentences = re.split(r'[.。!?！？]', text)
        if sentences and len(sentences[0]) > 10:
            first_sentence = sentences[0].strip()
            if len(first_sentence) <= max_length:
                return first_sentence
            else:
                # 如果第一句话太长，截取关键部分
                return first_sentence[:max_length] + '...'

        # 如果没有合适的句子，直接截取
        if len(text) <= max_length:
            return text
        return text[:max_length] + '...'

    def get_arxiv_papers(self) -> List[Dict[str, Any]]:
        """从arXiv获取AI论文"""
        print("📚 获取arXiv论文...")

        papers = []
        try:
            client = arxiv.Client()
            search = arxiv.Search(
                query="cat:cs.AI OR cat:cs.LG",
                max_results=10,  # 获取更多以便筛选
                sort_by=arxiv.SortCriterion.SubmittedDate,
                sort_order=arxiv.SortOrder.Descending
            )

            for result in client.results(search):
                # 生成一句话概要
                one_sentence = self.generate_one_sentence_summary(result.title)

                paper = {
                    'id': result.entry_id.split('/')[-1],
                    'title': result.title,
                    'one_sentence': one_sentence,  # 新增：一句话概要
                    'authors': [author.name for author in result.authors[:3]],
                    'summary': result.summary,
                    'published': result.published.strftime('%Y-%m-%d'),
                    'pdf_url': result.pdf_url,
                    'arxiv_url': f"https://arxiv.org/abs/{result.entry_id.split('/')[-1]}",
                    'category': result.primary_category
                }
                papers.append(paper)

                # 只保留前5篇
                if len(papers) >= 5:
                    break

            print(f"✅ 获取到 {len(papers)} 篇论文（从10篇中筛选）")

        except Exception as e:
            print(f"⚠️ 获取论文失败: {e}")
            # 返回示例数据
            papers = [{
                'id': '2401.12345',
                'title': 'Large Language Models: A Comprehensive Survey',
                'one_sentence': 'Comprehensive survey of large language models and their applications',
                'authors': ['AI Researcher', 'ML Expert'],
                'summary': 'Recent advances in large language models have revolutionized the field of artificial intelligence. These models, trained on massive datasets, demonstrate unprecedented capabilities in natural language understanding, generation, and reasoning.',
                'published': datetime.datetime.now().strftime('%Y-%m-%d'),
                'pdf_url': 'https://arxiv.org/pdf/2401.12345.pdf',
                'arxiv_url': 'https://arxiv.org/abs/2401.12345',
                'category': 'cs.AI'
            }]

        return papers

    def get_tech_news(self) -> List[Dict[str, Any]]:
        """获取科技新闻"""
        print("📰 获取科技新闻...")

        news_items = []
        try:
            # 使用MIT Technology Review的RSS
            feed = feedparser.parse('https://www.technologyreview.com/feed/')

            for entry in feed.entries[:10]:  # 获取更多以便筛选
                # 过滤AI相关新闻
                text = f"{entry.title} {entry.get('summary', '')}"
                if any(keyword in text.lower() for keyword in ['ai', 'artificial intelligence', 'machine learning']):
                    # 生成一句话概要
                    summary_text = entry.get('summary', entry.title)
                    one_sentence = self.generate_one_sentence_summary(summary_text, max_length=80)

                    news = {
                        'title': entry.title,
                        'one_sentence': one_sentence,  # 新增：一句话概要
                        'source': 'MIT Technology Review',
                        'link': entry.link,
                        'summary': entry.get('summary', ''),
                        'published': entry.get('published', datetime.datetime.now().strftime('%Y-%m-%d')),
                    }
                    news_items.append(news)

                    # 只保留前5条
                    if len(news_items) >= 5:
                        break

            print(f"✅ 获取到 {len(news_items)} 条新闻（从AI相关新闻中筛选）")

        except Exception as e:
            print(f"⚠️ 获取新闻失败: {e}")
            # 返回示例数据
            news_items = [{
                'title': 'Major AI Breakthrough Announced by Research Team',
                'one_sentence': 'New AI model achieves human-level performance on cognitive tasks',
                'source': 'Tech News',
                'link': 'https://example.com',
                'summary': 'Major breakthrough in artificial intelligence has been announced by researchers at a leading tech lab.',
                'published': datetime.datetime.now().strftime('%Y-%m-%d'),
            }]

        return news_items

    def generate_html(self, papers: List[Dict], news: List[Dict]) -> str:
        """生成HTML页面（改进版，参考ai-brief.liziran.com设计）"""
        now = datetime.datetime.now(pytz.timezone('Asia/Shanghai'))
        date_str = now.strftime('%Y年%m月%d日')
        date_str_en = now.strftime('%B %d, %Y')
        time_str = now.strftime('%H:%M:%S')

        # 构建改进版HTML
        html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI News Daily - liwenwei9</title>
    <meta name="description" content="每日AI资讯聚合网站 - 支持中英文切换">
    <style>
        :root {{
            --primary: #e74c3c;
            --primary-dark: #c0392b;
            --secondary: #34495e;
            --bg: #f8f9fa;
            --card: #ffffff;
            --text: #2c3e50;
            --text-light: #7f8c8d;
            --text-dark: #1a1a1a;
            --border: #e1e8ed;
            --number: #e74c3c;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
            line-height: 1.8;
            color: var(--text);
            background: var(--bg);
            min-height: 100vh;
        }}

        .container {{
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
        }}

        /* 导航栏 */
        .nav {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px 0;
            margin-bottom: 40px;
            border-bottom: 1px solid var(--border);
        }}

        .logo {{
            font-size: 1.5rem;
            font-weight: bold;
            color: var(--text-dark);
        }}

        .language-switcher {{
            display: flex;
            gap: 5px;
        }}

        .lang-btn {{
            padding: 6px 14px;
            border: 1px solid var(--border);
            background: white;
            color: var(--text-light);
            cursor: pointer;
            border-radius: 6px;
            font-size: 0.9rem;
            transition: all 0.3s;
            font-weight: 500;
        }}

        .lang-btn:hover {{
            border-color: var(--primary);
            color: var(--primary);
        }}

        .lang-btn.active {{
            background: var(--primary);
            color: white;
            border-color: var(--primary);
        }}

        /* 头部标语 */
        .hero {{
            text-align: center;
            padding: 60px 20px;
            margin-bottom: 40px;
        }}

        .hero h1 {{
            font-size: 2.8rem;
            color: var(--text-dark);
            margin-bottom: 15px;
            font-weight: 700;
        }}

        .hero .slogan {{
            font-size: 1.3rem;
            color: var(--text-light);
            margin-bottom: 25px;
            font-weight: 400;
        }}

        .date-badge {{
            display: inline-block;
            padding: 10px 25px;
            background: var(--primary);
            color: white;
            border-radius: 25px;
            font-size: 1rem;
            font-weight: 500;
            box-shadow: 0 4px 12px rgba(231, 76, 60, 0.2);
        }}

        /* 统计信息 */
        .stats {{
            display: flex;
            justify-content: center;
            gap: 40px;
            margin: 30px 0 50px;
            flex-wrap: wrap;
        }}

        .stat-item {{
            text-align: center;
        }}

        .stat-number {{
            font-size: 2.5rem;
            font-weight: bold;
            color: var(--primary);
            display: block;
            margin-bottom: 5px;
        }}

        .stat-label {{
            color: var(--text-light);
            font-size: 0.95rem;
        }}

        /* 内容区域 */
        .content {{
            background: var(--card);
            border-radius: 12px;
            padding: 40px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.04);
            margin-bottom: 30px;
        }}

        .section {{
            margin-bottom: 50px;
        }}

        .section:last-child {{
            margin-bottom: 0;
        }}

        .section-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 2px solid var(--primary);
        }}

        .section-title {{
            font-size: 1.6rem;
            color: var(--text-dark);
            font-weight: 700;
        }}

        .section-meta {{
            color: var(--text-light);
            font-size: 0.9rem;
        }}

        /* 论文/新闻条目 */
        .item {{
            margin-bottom: 30px;
            padding-bottom: 30px;
            border-bottom: 1px solid var(--border);
        }}

        .item:last-child {{
            margin-bottom: 0;
            padding-bottom: 0;
            border-bottom: none;
        }}

        .item-header {{
            display: flex;
            gap: 20px;
            margin-bottom: 15px;
        }}

        .item-number {{
            flex-shrink: 0;
            width: 50px;
            height: 50px;
            background: linear-gradient(135deg, var(--primary), var(--primary-dark));
            color: white;
            border-radius: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.4rem;
            font-weight: bold;
            box-shadow: 0 4px 12px rgba(231, 76, 60, 0.25);
        }}

        .item-content {{
            flex: 1;
            min-width: 0;
        }}

        .item-title {{
            font-size: 1.3rem;
            color: var(--text-dark);
            margin-bottom: 10px;
            font-weight: 700;
            line-height: 1.5;
            cursor: pointer;
            transition: color 0.3s;
        }}

        .item-title:hover {{
            color: var(--primary);
        }}

        .item-one-sentence {{
            font-size: 1rem;
            color: var(--text);
            margin-bottom: 15px;
            padding-left: 15px;
            border-left: 3px solid var(--primary);
            line-height: 1.7;
            font-weight: 500;
        }}

        .item-meta {{
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            margin-bottom: 15px;
            font-size: 0.9rem;
            color: var(--text-light);
        }}

        .meta-item {{
            display: flex;
            align-items: center;
            gap: 5px;
        }}

        .item-summary {{
            color: var(--text);
            line-height: 1.8;
            margin-bottom: 20px;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
            font-size: 0.95rem;
            white-space: pre-wrap;
            word-wrap: break-word;
        }}

        .item-actions {{
            display: flex;
            gap: 10px;
            flex-wrap: wrap;
        }}

        .btn {{
            display: inline-flex;
            align-items: center;
            gap: 5px;
            padding: 8px 20px;
            background: var(--primary);
            color: white !important;
            text-decoration: none;
            border-radius: 6px;
            font-size: 0.9rem;
            font-weight: 500;
            transition: all 0.3s;
            border: none;
            cursor: pointer;
        }}

        .btn:hover {{
            background: var(--primary-dark);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(231, 76, 60, 0.3);
        }}

        .btn-secondary {{
            background: var(--secondary);
        }}

        .btn-secondary:hover {{
            background: #2c3e50;
        }}

        /* 页脚 */
        footer {{
            text-align: center;
            padding: 40px 20px;
            color: var(--text-light);
            margin-top: 50px;
            border-top: 1px solid var(--border);
        }}

        footer p {{
            margin: 10px 0;
            font-size: 0.95rem;
        }}

        footer a {{
            color: var(--primary) !important;
            text-decoration: none;
            font-weight: 600;
        }}

        footer a:hover {{
            text-decoration: underline;
        }}

        /* 响应式设计 */
        @media (max-width: 768px) {{
            .container {{
                padding: 15px;
            }}

            .hero h1 {{
                font-size: 2rem;
            }}

            .hero .slogan {{
                font-size: 1.1rem;
            }}

            .content {{
                padding: 25px;
            }}

            .item-number {{
                width: 40px;
                height: 40px;
                font-size: 1.2rem;
            }}

            .item-title {{
                font-size: 1.1rem;
            }}

            .stats {{
                gap: 25px;
            }}

            .stat-number {{
                font-size: 2rem;
            }}
        }}

        /* 加载动画 */
        @keyframes fadeIn {{
            from {{ opacity: 0; transform: translateY(20px); }}
            to {{ opacity: 1; transform: translateY(0); }}
        }}

        .item {{
            animation: fadeIn 0.6s ease-out;
        }}
    </style>
</head>
<body>
    <div class="container">
        <!-- 导航栏 -->
        <nav class="nav">
            <div class="logo" data-zh="AI论文简报" data-en="AI News Daily">AI论文简报</div>
            <div class="language-switcher">
                <button class="lang-btn active" data-lang="zh">中文</button>
                <button class="lang-btn" data-lang="en">EN</button>
            </div>
        </nav>

        <!-- 英雄区域 -->
        <div class="hero">
            <h1 data-zh="AI News Daily" data-en="AI News Daily">AI News Daily</h1>
            <div class="slogan" data-zh="每天3分钟，把握AI前沿动态" data-en="3 minutes a day to stay ahead in AI">每天3分钟，把握AI前沿动态</div>
            <div class="date-badge">
                <span data-zh="📅 {date_str}" data-en="📅 {date_str_en}">📅 {date_str}</span>
            </div>

            <div class="stats">
                <div class="stat-item">
                    <span class="stat-number">{len(papers)}</span>
                    <span class="stat-label" data-zh="📚 今日论文" data-en="📚 Papers">📚 今日论文</span>
                </div>
                <div class="stat-item">
                    <span class="stat-number">{len(news)}</span>
                    <span class="stat-label" data-zh="📰 今日新闻" data-en="📰 News">📰 今日新闻</span>
                </div>
                <div class="stat-item">
                    <span class="stat-number">{len(papers) + len(news)}</span>
                    <span class="stat-label" data-zh="✨ 总计内容" data-en="✨ Total">✨ 总计内容</span>
                </div>
            </div>
        </div>

        <!-- 内容区域 -->
        <div class="content">
            <!-- 论文部分 -->
            <section class="section">
                <div class="section-header">
                    <h2 class="section-title" data-zh="📚 今日论文精选" data-en="📚 Today's Paper Selection">📚 今日论文精选</h2>
                    <div class="section-meta" data-zh="从10篇论文中筛选" data-en="Selected from 10 papers">从10篇论文中筛选</div>
                </div>
                {self._generate_papers_html(papers)}
            </section>

            <!-- 新闻部分 -->
            <section class="section">
                <div class="section-header">
                    <h2 class="section-title" data-zh="📰 今日新闻精选" data-en="📰 Today's News Selection">📰 今日新闻精选</h2>
                    <div class="section-meta" data-zh="AI相关新闻" data-en="AI-related news">AI相关新闻</div>
                </div>
                {self._generate_news_html(news)}
            </section>
        </div>

        <!-- 页脚 -->
        <footer>
            <p data-zh="🤖 由AI自动生成 | 每日更新 | liwenwei9的专属版本" data-en="🤖 Auto-generated by AI | Daily Update | liwenwei9 Exclusive">🤖 由AI自动生成 | 每日更新 | liwenwei9的专属版本</p>
            <p data-zh="📅 最后更新: {date_str} | ⏰ 生成时间: {time_str}" data-en="📅 Last Update: {date_str_en} | ⏰ Generated: {time_str}">📅 最后更新: {date_str} | ⏰ 生成时间: {time_str}</p>
            <p>🚀 <a href="https://github.com/{self.github_user}/{self.repo_name}" target="_blank" data-zh="查看GitHub项目" data-en="View on GitHub">查看GitHub项目</a></p>
        </footer>
    </div>

    <script>
        // 多语言支持
        function getCurrentLanguage() {{
            return localStorage.getItem('ai-news-language') || 'zh';
        }}

        function saveLanguage(lang) {{
            localStorage.setItem('ai-news-language', lang);
        }}

        function switchLanguage(lang) {{
            // 更新按钮状态
            document.querySelectorAll('.lang-btn').forEach(btn => {{
                btn.classList.remove('active');
                if (btn.dataset.lang === lang) {{
                    btn.classList.add('active');
                }}
            }});

            // 更新所有带data属性的元素
            document.querySelectorAll('[data-zh], [data-en]').forEach(element => {{
                if (element.dataset[lang]) {{
                    element.textContent = element.dataset[lang];
                }}
            }});

            // 更新页面标题
            document.title = lang === 'zh' ? 'AI News Daily - liwenwei9' : 'AI News Daily - liwenwei9';

            // 更新HTML lang属性
            document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';

            // 保存选择
            saveLanguage(lang);
        }}

        // 初始化
        document.addEventListener('DOMContentLoaded', function() {{
            const currentLang = getCurrentLanguage();
            switchLanguage(currentLang);

            // 添加按钮点击事件
            document.querySelectorAll('.lang-btn').forEach(btn => {{
                btn.addEventListener('click', function() {{
                    switchLanguage(this.dataset.lang);
                }});
            }});
        }});
    </script>
</body>
</html>'''
        return html

    def _generate_papers_html(self, papers: List[Dict]) -> str:
        """生成论文HTML（改进版）"""
        if not papers:
            return '<p class="empty-message" data-zh="暂无论文数据" data-en="No papers available">暂无论文数据</p>'

        html_parts = []
        for idx, paper in enumerate(papers, 1):
            # 格式化作者列表
            authors_str = ', '.join(paper['authors'])
            if len(paper['authors']) >= 3:
                authors_str += ' et al.'

            html = f'''
            <div class="item">
                <div class="item-header">
                    <div class="item-number">{idx:02d}</div>
                    <div class="item-content">
                        <h3 class="item-title">{paper['title']}</h3>
                        <div class="item-one-sentence">{paper['one_sentence']}</div>
                        <div class="item-meta">
                            <div class="meta-item">
                                <span>👨‍🎓</span>
                                <span data-zh="作者" data-en="Authors">作者</span>: {authors_str}
                            </div>
                            <div class="meta-item">
                                <span>🏷️</span>
                                <span data-zh="分类" data-en="Category">分类</span>: {paper['category']}
                            </div>
                            <div class="meta-item">
                                <span>📅</span>
                                <span>{paper['published']}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item-summary">{paper['summary']}</div>
                <div class="item-actions">
                    <a href="{paper['pdf_url']}" class="btn" target="_blank">
                        <span>📄</span>
                        <span data-zh="下载PDF" data-en="Download PDF">下载PDF</span>
                    </a>
                    <a href="{paper['arxiv_url']}" class="btn btn-secondary" target="_blank">
                        <span>🔗</span>
                        <span data-zh="arXiv页面" data-en="arXiv Page">arXiv页面</span>
                    </a>
                </div>
            </div>
            '''
            html_parts.append(html)

        return '\n'.join(html_parts)

    def _generate_news_html(self, news: List[Dict]) -> str:
        """生成新闻HTML（改进版）"""
        if not news:
            return '<p class="empty-message" data-zh="暂无新闻数据" data-en="No news available">暂无新闻数据</p>'

        html_parts = []
        for idx, item in enumerate(news, 1):
            html = f'''
            <div class="item">
                <div class="item-header">
                    <div class="item-number">{idx:02d}</div>
                    <div class="item-content">
                        <h3 class="item-title">{item['title']}</h3>
                        <div class="item-one-sentence">{item['one_sentence']}</div>
                        <div class="item-meta">
                            <div class="meta-item">
                                <span>🏢</span>
                                <span data-zh="来源" data-en="Source">来源</span>: {item['source']}
                            </div>
                            <div class="meta-item">
                                <span>📅</span>
                                <span>{item['published']}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item-summary">{item['summary']}</div>
                <div class="item-actions">
                    <a href="{item['link']}" class="btn" target="_blank">
                        <span>🔗</span>
                        <span data-zh="阅读原文" data-en="Read Original">阅读原文</span>
                    </a>
                </div>
            </div>
            '''
            html_parts.append(html)

        return '\n'.join(html_parts)

    def run(self):
        """主运行函数"""
        print("🚀 AI News Daily 开始运行（改进版）...")
        print(f"👤 GitHub用户: {self.github_user}")
        print(f"🌐 网站地址: {self.website_url}")
        print("🌐 支持语言: 中文 / English")
        print("✨ 新功能: 一句话概要 | 改进排版 | 编号系统")

        try:
            # 获取数据
            papers = self.get_arxiv_papers()
            news = self.get_tech_news()

            # 生成HTML
            html = self.generate_html(papers, news)

            # 保存文件
            with open('docs/index.html', 'w', encoding='utf-8') as f:
                f.write(html)

            print("✅ 网站生成完成！")
            print(f"📁 文件保存: docs/index.html")
            print(f"🌐 访问地址: {self.website_url}")
            print("🎯 功能: 中英文切换 | 一句话概要 | 完整摘要 | PDF/arXiv链接 | 每日自动更新")

        except Exception as e:
            print(f"❌ 运行失败: {e}")
            import traceback
            traceback.print_exc()

if __name__ == '__main__':
    app = AINewsDaily()
    app.run()
