#!/usr/bin/env python3
"""
AI News Daily - liwenwei9 专属版本（支持中英文）
"""


import os
import datetime
import pytz
from typing import List, Dict, Any
import arxiv
import feedparser

class AINewsDaily:
    def __init__(self):
        self.github_user = "liwenwei9"
        self.repo_name = "ai-news-daily"
        self.website_url = f"https://{self.github_user}.github.io/{self.repo_name}/"
        os.makedirs('docs', exist_ok=True)

        self.texts = {
            'zh': {
                'site_title': 'AI News Daily - liwenwei9',
                'subtitle': 'liwenwei9 的专属AI资讯站',
                'today_papers': '📚 今日论文',
                'today_news': '📰 今日新闻',
                'total_content': '✨ 总计内容',
                'paper_selection': '📚 今日论文精选',
                'news_selection': '📰 今日新闻精选',
                'authors': '👨‍🎓 作者',
                'category': '🏷️ 分类',
                'date': '📅 日期',
                'source': '🏢 来源',
                'download_pdf': '📄 下载PDF',
                'arxiv_page': '🔗 arXiv页面',
                'read_original': '🔗 阅读原文',
                'auto_generated': '由 AI 自动生成',
                'daily_update': '每日更新',
                'exclusive_version': 'liwenwei9 专属版本',
                'last_update': '📅 最后更新',
                'generation_time': '⏰ 生成时间',
                'view_project': '查看 GitHub 项目',
                'no_paper_data': '暂无论文数据',
                'no_news_data': '暂无新闻数据',
                'current_time': '⏰ 当前时间',
                'published': '发布时间',
                'footer_desc': '🤖 由 AI 自动生成 | 每日更新 | liwenwei9 的专属版本',
            },
            'en': {
                'site_title': 'AI News Daily - liwenwei9',
                'subtitle': 'liwenwei9\'s Exclusive AI News Station',
                'today_papers': '📚 Today\'s Papers',
                'today_news': '📰 Today\'s News',
                'total_content': '✨ Total Content',
                'paper_selection': '📚 Today\'s Paper Selection',
                'news_selection': '📰 Today\'s News Selection',
                'authors': '👨‍🎓 Authors',
                'category': '🏷️ Category',
                'date': '📅 Date',
                'source': '🏢 Source',
                'download_pdf': '📄 Download PDF',
                'arxiv_page': '🔗 arXiv Page',
                'read_original': '🔗 Read Original',
                'auto_generated': 'Auto-generated by AI',
                'daily_update': 'Daily Update',
                'exclusive_version': 'liwenwei9 Exclusive Version',
                'last_update': '📅 Last Update',
                'generation_time': '⏰ Generation Time',
                'view_project': 'View GitHub Project',
                'no_paper_data': 'No paper data available',
                'no_news_data': 'No news data available',
                'current_time': '⏰ Current Time',
                'published': 'Published',
                'footer_desc': '🤖 Auto-generated by AI | Daily Update | liwenwei9 Exclusive Version',
            }
        }

    def get_arxiv_papers(self) -> List[Dict[str, Any]]:
        print("📚 获取arXiv论文...")
        papers = []
        try:
            client = arxiv.Client()
            search = arxiv.Search(
                query="cat:cs.AI OR cat:cs.LG",
                max_results=5,
                sort_by=arxiv.SortCriterion.SubmittedDate,
                sort_order=arxiv.SortOrder.Descending
            )
            for res in client.results(search):
                papers.append({
                    "id": res.entry_id.split('/')[-1],
                    "title": res.title,
                    "authors": [a.name for a in res.authors[:3]],
                    "summary": res.summary,  # 完整摘要
                    "published": res.published.strftime('%Y-%m-%d'),
                    "pdf_url": res.pdf_url,
                    "arxiv_url": f"https://arxiv.org/abs/{res.entry_id.split('/')[-1]}",
                    "category": res.primary_category
                })
            print(f"✅ 获取到 {len(papers)} 篇论文")
        except Exception as e:
            print(f"⚠️ 获取论文失败: {e}")
            papers = [{
                "id": "2401.12345",
                "title": "Large Language Models: A Survey",
                "authors": ["AI Researcher"],
                "summary": "Recent advances in large language models...",
                "published": datetime.datetime.now().strftime('%Y-%m-%d'),
                "pdf_url": "https://arxiv.org/pdf/2401.12345.pdf",
                "arxiv_url": "https://arxiv.org/abs/2401.12345",
                "category": "cs.AI"
            }]
        return papers

    def get_tech_news(self) -> List[Dict[str, Any]]:
        print("📰 获取科技新闻...")
        news = []
        try:
            feed = feedparser.parse('https://www.technologyreview.com/feed/')
            for entry in feed.entries[:5]:
                txt = (entry.title + " " + entry.get('summary', '')).lower()
                if any(k in txt for k in ['ai', 'artificial intelligence', 'machine learning']):
                    news.append({
                        "title": entry.title,
                        "source": "MIT Technology Review",
                        "link": entry.link,
                        "summary": entry.get('summary', ''),  # 完整摘要
                        "published": entry.get('published', datetime.datetime.now().strftime('%Y-%m-%d')),
                    })
            print(f"✅ 获取到 {len(news)} 条新闻")
        except Exception as e:
            print(f"⚠️ 获取新闻失败: {e}")
            news = [{
                "title": "AI Breakthrough Announced",
                "source": "Tech News",
                "link": "https://example.com",
                "summary": "Major breakthrough in artificial intelligence...",
                "published": datetime.datetime.now().strftime('%Y-%m-%d'),
            }]
        return news

    def generate_html(self, papers: List[Dict], news: List[Dict]) -> str:
        tz = pytz.timezone('Asia/Shanghai')
        now = datetime.datetime.now(tz)
        date_str = now.strftime('%Y-%m-%d')
        time_str = now.strftime('%H:%M:%S')

        html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI News Daily</title>
    <style>
        :root {{ --primary:#667eea; --secondary:#764ba2; --bg:#f5f7fa; --card:#fff; --text:#333; }}
        *{{margin:0;padding:0;box-sizing:border-box;}}
        body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;line-height:1.6;background:var(--bg);color:var(--text);}}
        .container{{max-width:1000px;margin:0 auto;padding:20px;}}
        .language-switcher{{position:fixed;top:20px;right:20px;z-index:1000;background:rgba(255,255,255,0.9);padding:8px 12px;border-radius:20px;box-shadow:0 2px 10px rgba(0,0,0,0.1);}}
        .lang-btn{{border:none;background:transparent;padding:6px 12px;border-radius:15px;cursor:pointer;}}
        .lang-btn.active{{background:var(--primary);color:white;}}
        header{{text-align:center;padding:30px;background:linear-gradient(135deg,var(--primary),var(--secondary));color:white;border-radius:10px;margin-bottom:30px;}}
        h1{{font-size:2.5rem;margin-bottom:10px;}}
        .stats{{display:flex;justify-content:center;gap:20px;margin:20px 0;flex-wrap:wrap;}}
        .stat-card{{background:rgba(255,255,255,0.9);padding:15px 25px;border-radius:10px;min-width:120px;text-align:center;}}
        .stat-number{{font-size:1.8rem;font-weight:bold;color:var(--primary);}}
        .content{{background:var(--card);border-radius:15px;padding:30px;box-shadow:0 5px 15px rgba(0,0,0,0.08);}}
        .section{{margin-bottom:30px;}}
        .section-title{{font-size:1.5rem;margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid var(--primary);}}
        .item-card{{background:#f8f9fa;border-radius:10px;padding:20px;margin-bottom:15px;border-left:3px solid var(--primary);}}
        .item-title{{font-size:1.2rem;margin-bottom:10px;}}
        .item-meta{{display:flex;flex-wrap:wrap;gap:15px;color:#666;font-size:0.9rem;margin-bottom:10px;}}
        .item-summary{{background:white;padding:15px;border-radius:8px;line-height:1.6;color:#444;white-space:pre-line;}}
        .btn{{display:inline-block;padding:8px 16px;background:var(--primary);color:white;text-decoration:none;border-radius:6px;margin-right:10px;}}
        footer{{text-align:center;padding:30px;color:#666;margin-top:30px;}}
    </style>
</head>
<body>
<div class="language-switcher">
    <button class="lang-btn active" data-lang="zh">中文</button>
    <button class="lang-btn" data-lang="en">English</button>
</div>

<div class="container">
    <header>
        <h1 data-i18n="site_title">🤖 AI News Daily</h1>
        <div class="subtitle" data-i18n="subtitle">liwenwei9 的专属AI资讯站</div>
        <div class="stats">
            <div class="stat-card"><div class="stat-number">{len(papers)}</div><div data-i18n="today_papers">📚 今日论文</div></div>
            <div class="stat-card"><div class="stat-number">{len(news)}</div><div data-i18n="today_news">📰 今日新闻</div></div>
            <div class="stat-card"><div class="stat-number">{len(papers)+len(news)}</div><div data-i18n="total_content">✨ 总计内容</div></div>
        </div>
    </header>

    <div class="content">
        <section class="section">
            <h2 class="section-title" data-i18n="paper_selection">📚 今日论文精选</h2>
            {self._paper_html(papers)}
        </section>
        <section class="section">
            <h2 class="section-title" data-i18n="news_selection">📰 今日新闻精选</h2>
            {self._news_html(news)}
        </section>
    </div>

    <footer>
        <p data-i18n="footer_desc">🤖 由 AI 自动生成 | 每日更新 | liwenwei9 的专属版本</p>
        <p><span data-i18n="last_update">最后更新</span>: {date_str} | <span data-i18n="current_time">当前时间</span>: <span id="t">{time_str}</span></p>
        <p><a href="https://github.com/{self.github_user}/{self.repo_name}" target="_blank" style="color:#667eea" data-i18n="view_project">查看 GitHub 项目</a></p>
    </footer>
</div>

<script>
const translations = {
    zh: {
        site_title: "🤖 AI News Daily",
        subtitle: "liwenwei9 的专属AI资讯站",
        today_papers: "📚 今日论文",
        today_news: "📰 今日新闻",
        total_content: "✨ 总计内容",
        paper_selection: "📚 今日论文精选",
        news_selection: "📰 今日新闻精选",
        authors: "👨‍🎓 作者",
        category: "🏷️ 分类",
        date: "📅 日期",
        source: "🏢 来源",
        download_pdf: "📄 下载PDF",
        arxiv_page: "🔗 arXiv页面",
        read_original: "🔗 阅读原文",
        last_update: "📅 最后更新",
        current_time: "⏰ 当前时间",
        view_project: "查看 GitHub 项目",
        no_paper_data: "暂无论文数据",
        no_news_data: "暂无新闻数据",
        footer_desc: "🤖 由 AI 自动生成 | 每日更新 | liwenwei9 的专属版本"
    },
    en: {
        site_title: "🤖 AI News Daily",
        subtitle: "liwenwei9's Exclusive AI News Station",
        today_papers: "📚 Today's Papers",
        today_news: "📰 Today's News",
        total_content: "✨ Total Content",
        paper_selection: "📚 Today's Paper Selection",
        news_selection: "📰 Today's News Selection",
        authors: "👨‍🎓 Authors",
        category: "🏷️ Category",
        date: "📅 Date",
        source: "🏢 Source",
        download_pdf: "📄 Download PDF",
        arxiv_page: "🔗 arXiv Page",
        read_original: "🔗 Read Original",
        last_update: "📅 Last Update",
        current_time: "⏰ Current Time",
        view_project: "View GitHub Project",
        no_paper_data: "No paper data available",
        no_news_data: "No news data available",
        footer_desc: "🤖 Auto-generated by AI | Daily Update | liwenwei9 Exclusive Version"
    }
};

let currentLang = localStorage.getItem('lang') || 'zh';

function updateLang(lang) {
    currentLang = lang;
    localStorage.setItem('lang', lang);
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const k = el.dataset.i18n;
        if (translations[lang][k]) el.textContent = translations[lang][k];
    });
    document.querySelectorAll('.lang-btn').forEach(b => b.classList.remove('active'));
    document.querySelector(`[data-lang="${lang}"]`).classList.add('active');
}

document.querySelectorAll('.lang-btn').forEach(b => {
    b.addEventListener('click', () => updateLang(b.dataset.lang));
});

updateLang(currentLang);

setInterval(() => {
    const now = new Date();
    document.getElementById('t').textContent = currentLang === 'zh'
        ? now.toLocaleTimeString('zh-CN')
        : now.toLocaleTimeString('en-US');
}, 1000);
</script>
</body>
</html>'''
        return html

    def _paper_html(self, papers):
        if not papers:
            return '<p data-i18n="no_paper_data">暂无论文数据</p>'
        parts = []
        for p in papers:
            summary = p["summary"].replace('\n', ' ').strip()
            parts.append(f'''
            <div class="item-card">
                <h3 class="item-title">{p["title"]}</h3>
                <div class="item-meta">
                    <span data-i18n="authors">作者</span>: {', '.join(p["authors"])} &nbsp;
                    <span data-i18n="category">分类</span>: {p["category"]} &nbsp;
                    <span data-i18n="date">日期</span>: {p["published"]}
                </div>
                <div class="item-summary">{summary}</div>
                <div>
                    <a href="{p["pdf_url"]}" class="btn" target="_blank" data-i18n="download_pdf">下载PDF</a>
                    <a href="{p["arxiv_url"]}" class="btn" target="_blank" data-i18n="arxiv_page">arXiv页面</a>
                </div>
            </div>''')
        return '\n'.join(parts)

    def _news_html(self, news):
        if not news:
            return '<p data-i18n="no_news_data">暂无新闻数据</p>'
        parts = []
        for n in news:
            s = n["summary"].replace('\n', ' ').strip()
            parts.append(f'''
            <div class="item-card">
                <h3 class="item-title">{n["title"]}</h3>
                <div class="item-meta">
                    <span data-i18n="source">来源</span>: {n["source"]} &nbsp;
                    <span data-i18n="published">发布时间</span>: {n["published"]}
                </div>
                <div class="item-summary">{s}</div>
                <div>
                    <a href="{n["link"]}" class="btn" target="_blank" data-i18n="read_original">阅读原文</a>
                </div>
            </div>''')
        return '\n'.join(parts)

    def run(self):
        print("🚀 AI News Daily 开始运行...")
        try:
            papers = self.get_arxiv_papers()
            news = self.get_tech_news()
            html = self.generate_html(papers, news)
            with open('docs/index.html', 'w', encoding='utf-8') as f:
                f.write(html)
            print("✅ 生成完成：docs/index.html")
        except Exception as e:
            print(f"❌ 失败：{e}")

if __name__ == '__main__':
    AINewsDaily().run()
